// <auto-generated />
using System;
using Media_Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Media_Database.Migrations
{
    [DbContext(typeof(MediaContext))]
    [Migration("20260712153458_EnforceShowSeasonEpisodeFlow")]
    partial class EnforceShowSeasonEpisodeFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Media_Database.Models.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MovieId");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("Media_Database.Models.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Media_Database.Models.Director", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MovieId");

                    b.ToTable("Directors");
                });

            modelBuilder.Entity("Media_Database.Models.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<bool?>("FirstWatch")
                        .HasColumnType("bit");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LengthMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int?>("Rewatchability")
                        .HasColumnType("int");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Synopsis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("WatchDate")
                        .HasColumnType("date");

                    b.Property<bool?>("Watched")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Media_Database.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MovieId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Media_Database.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FirstWatch")
                        .HasColumnType("bit");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LengthMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ReleaseYear")
                        .HasColumnType("date");

                    b.Property<int?>("Rewatchability")
                        .HasColumnType("int");

                    b.Property<string>("Synopsis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("WatchDate")
                        .HasColumnType("date");

                    b.Property<bool?>("Watched")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Media_Database.Models.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ReleaseYear")
                        .HasColumnType("date");

                    b.Property<Guid>("ShowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Synopsis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("ShowId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Media_Database.Models.Show", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ReleaseYear")
                        .HasColumnType("date");

                    b.Property<string>("Synopsis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WatchStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("Media_Database.Models.Writer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MovieId");

                    b.ToTable("Writers");
                });

            modelBuilder.Entity("Media_Database.Models.Actor", b =>
                {
                    b.HasOne("Media_Database.Models.Episode", "Episode")
                        .WithMany("Actors")
                        .HasForeignKey("EpisodeId");

                    b.HasOne("Media_Database.Models.Movie", "Movie")
                        .WithMany("Actors")
                        .HasForeignKey("MovieId");

                    b.Navigation("Episode");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Media_Database.Models.Director", b =>
                {
                    b.HasOne("Media_Database.Models.Episode", "Episode")
                        .WithMany("Directors")
                        .HasForeignKey("EpisodeId");

                    b.HasOne("Media_Database.Models.Movie", "Movie")
                        .WithMany("Directors")
                        .HasForeignKey("MovieId");

                    b.Navigation("Episode");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Media_Database.Models.Episode", b =>
                {
                    b.HasOne("Media_Database.Models.Collection", "Collection")
                        .WithMany("Episodes")
                        .HasForeignKey("CollectionId");

                    b.HasOne("Media_Database.Models.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Media_Database.Models.Genre", b =>
                {
                    b.HasOne("Media_Database.Models.Episode", "Episode")
                        .WithMany("Genres")
                        .HasForeignKey("EpisodeId");

                    b.HasOne("Media_Database.Models.Movie", "Movie")
                        .WithMany("Genres")
                        .HasForeignKey("MovieId");

                    b.Navigation("Episode");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Media_Database.Models.Movie", b =>
                {
                    b.HasOne("Media_Database.Models.Collection", null)
                        .WithMany("Movies")
                        .HasForeignKey("CollectionId");
                });

            modelBuilder.Entity("Media_Database.Models.Season", b =>
                {
                    b.HasOne("Media_Database.Models.Collection", null)
                        .WithMany("Seasons")
                        .HasForeignKey("CollectionId");

                    b.HasOne("Media_Database.Models.Show", "Show")
                        .WithMany("Seasons")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Media_Database.Models.Show", b =>
                {
                    b.HasOne("Media_Database.Models.Collection", null)
                        .WithMany("Shows")
                        .HasForeignKey("CollectionId");
                });

            modelBuilder.Entity("Media_Database.Models.Writer", b =>
                {
                    b.HasOne("Media_Database.Models.Episode", "Episode")
                        .WithMany("Writers")
                        .HasForeignKey("EpisodeId");

                    b.HasOne("Media_Database.Models.Movie", "Movie")
                        .WithMany("Writers")
                        .HasForeignKey("MovieId");

                    b.Navigation("Episode");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Media_Database.Models.Collection", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("Movies");

                    b.Navigation("Seasons");

                    b.Navigation("Shows");
                });

            modelBuilder.Entity("Media_Database.Models.Episode", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Directors");

                    b.Navigation("Genres");

                    b.Navigation("Writers");
                });

            modelBuilder.Entity("Media_Database.Models.Movie", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Directors");

                    b.Navigation("Genres");

                    b.Navigation("Writers");
                });

            modelBuilder.Entity("Media_Database.Models.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("Media_Database.Models.Show", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
